# Generated by Django 5.1.2 on 2024-11-17 11:14

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20, null=True)),
                ('intial', models.CharField(max_length=1)),
                ('proflie_pic', models.ImageField(blank=True, null=True, upload_to=core.models.profile_path)),
                ('dept', models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Information Technology', 'IT'), ('Instrumentation and Controls Engineering', 'IT'), ('Electrical and Electronics Engineering', 'EEE')], max_length=50)),
                ('gender', models.BooleanField(choices=[(1, 'male'), (0, 'female')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('regno', models.BigIntegerField(unique=True)),
                ('dept', models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Information Technology', 'IT'), ('Instrumentation and Controls Engineering', 'IT'), ('Electrical and Electronics Engineering', 'EEE')], max_length=50)),
                ('section', models.CharField(max_length=1)),
                ('semester', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=6)),
                ('semester', models.SmallIntegerField()),
                ('mcourse', models.BooleanField(default=False, help_text='manitaory course')),
                ('ecourse', models.BooleanField(default=False, help_text='elective course')),
                ('oecourse', models.BooleanField(default=False, help_text='open elective course')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.SmallIntegerField()),
                ('section', models.CharField(max_length=1)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'verbose_name': 'handling class',
            },
        ),
    ]
