# Generated by Django 5.1.2 on 2024-10-12 12:28

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('regno', models.BigIntegerField()),
                ('dept', models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Tnformation Technology', 'IT'), ('Instrumentation and Controls Engineering', 'IT'), ('Electrical and Electronics Engineering', 'EEE')], max_length=50)),
                ('section', models.CharField(max_length=1)),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=6)),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('intial', models.CharField(max_length=1)),
                ('proflie_pic', models.ImageField(blank=True, null=True, upload_to=core.models.profile_path)),
                ('dept', models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Tnformation Technology', 'IT'), ('Instrumentation and Controls Engineering', 'IT'), ('Electrical and Electronics Engineering', 'EEE')], max_length=50)),
                ('gender', models.BooleanField(choices=[(1, 'male'), (0, 'female')])),
                ('hclass', models.CharField(max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.SmallIntegerField()),
                ('cat2', models.SmallIntegerField()),
                ('cat3', models.SmallIntegerField()),
                ('cat4', models.SmallIntegerField()),
                ('cat5', models.SmallIntegerField()),
                ('cat6', models.SmallIntegerField()),
                ('cat7', models.SmallIntegerField()),
                ('cat8', models.SmallIntegerField()),
                ('cat9', models.SmallIntegerField()),
                ('cat10', models.SmallIntegerField()),
                ('avg_cat', models.FloatField(editable=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
