# Generated by Django 5.0.7 on 2024-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dept',
            field=models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Tnformation Technology', 'IT'), ('Instrumentation and Controls Engineering', 'IT'), ('Electrical and Electronics Engineering', 'EEE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Tnformation Technology', 'IT'), ('Instrumentation and Controls Engineering', 'IT'), ('Electrical and Electronics Engineering', 'EEE')], max_length=50),
        ),
    ]
