# Generated by Django 5.1.2 on 2024-11-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_ecourse_subject_oecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
