# Generated by Django 5.1.3 on 2024-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_feed_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('dept', models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('MCA', 'mca'), ('MBA', 'mba')], max_length=10)),
            ],
        ),
    ]
