# Generated by Django 5.1.2 on 2024-10-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classstaff_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='mcourse',
            field=models.BooleanField(default=False, help_text='manitaory course'),
        ),
    ]
