# Generated by Django 5.0.7 on 2024-10-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
