# Generated by Django 5.1.3 on 2024-12-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timescheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstaff',
            name='msg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
