# Generated by Django 5.0.7 on 2024-10-06 11:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='intial',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='proflie_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_path),
        ),
        migrations.AddField(
            model_name='staff',
            name='sname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
