# Generated by Django 5.1.3 on 2024-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_classstaff_msg_feedback_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='feed',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feed1',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='feed2',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='feed1_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='feed2_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
