# Generated by Django 5.1.3 on 2024-12-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_timescheduler_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feed1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
