# Generated by Django 5.1.3 on 2025-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_feedback_feed1_alter_feedback_feed2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classstaff',
            options={'verbose_name': 'class handling'},
        ),
        migrations.AddField(
            model_name='timescheduler',
            name='feed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classstaff',
            name='dept',
            field=models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil'), ('MCA', 'mca'), ('MBA', 'mba')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dept',
            field=models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil'), ('MCA', 'mca'), ('MBA', 'mba')], max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dept',
            field=models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil'), ('MCA', 'mca'), ('MBA', 'mba')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil'), ('MCA', 'mca'), ('MBA', 'mba')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dept',
            field=models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil'), ('MCA', 'mca'), ('MBA', 'mba')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timescheduler',
            name='dept',
            field=models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil'), ('MCA', 'mca'), ('MBA', 'mba')], max_length=10),
        ),
    ]
