# Generated by Django 5.1.3 on 2025-01-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_classstaff_options_timescheduler_feed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
